"""RELATIONSHIP-FIX-1

Revision ID: 18bb9b7a56c4
Revises: eeb2b30b6f4b
Create Date: 2023-12-12 00:37:18.054291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bb9b7a56c4'
down_revision: Union[str, None] = 'eeb2b30b6f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
