"""RELATIONSHIP-FIX-2

Revision ID: a46478a00224
Revises: 18bb9b7a56c4
Create Date: 2023-12-12 00:39:54.298567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46478a00224'
down_revision: Union[str, None] = '18bb9b7a56c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
