"""TRANSACTIONS

Revision ID: ca54ed5f6a2d
Revises: e7c7f8c6e899
Create Date: 2023-12-12 00:04:02.251325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca54ed5f6a2d'
down_revision: Union[str, None] = 'e7c7f8c6e899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
