"""RELATIONSHIP-FIX

Revision ID: eeb2b30b6f4b
Revises: 75494d952393
Create Date: 2023-12-12 00:34:59.075697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb2b30b6f4b'
down_revision: Union[str, None] = '75494d952393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
